### PR TITLE
fix bug when disconnect call before successfully connected

### PR DESCRIPTION
**Pull request by 0x0a0d**
while using jest to test my service with real `mongodb`, I still got stuck with mongoose connection likes pull #233, which should be fixed. After researching, I found that while running tests, `broker.stop()` was called before mongodb connect successfully. In this case, `this.conn` is not `undefined` but `this.conn.close` (same with `this.conn.db`) still not created.
This pull changes something:
~~[x] remove `this.db`, I don't understand why we need this?~~
[x] adapter connection will be set to `this.conn`
[x] rewrite tests

### CODE REVIEW

**Review by icebob — CHANGES_REQUESTED** [review]
Removing `this.db` causes breaking change, because some users can use as `this.adapter.db` in their services.

**Comment by 0x0a0d** [comment]
> Removing `this.db` causes breaking change, because some users can use as `this.adapter.db` in their services.

ok I will try to resolve this, maybe next week if having freetime

**Comment by 0x0a0d** [comment]
updated mongoose tests and `this.db`

**Comment by 0x0a0d** [comment]
@icebob

**Comment by icebob** [comment]
Thanks for your work. I'm checking & testing the changes.

**Review by icebob — CHANGES_REQUESTED** [review]
I have more problems with the PR.
1. It contains a lot of changes which is not mentioned in the original problem
2. The whole connection logic has been changed and I don't understand why and which part does what and what is the difference.
3. I've tried to execute the examples but nothing work.

To be honest, I'm afraid to merge it.

**Pull request closed without merging**
