### PR TITLE
Using mongoose lean for queries

### PR DESCRIPTION
**Pull request by Pitbi**
Hello,

Following my issue #244, I tried a small modification. What do you think?

Thanks for reading me :)

### CODE REVIEW

**Review by icebob — CHANGES_REQUESTED** [review]
Hi, thanks for the PR, but I can't merge it, because it causes breaking changes a lot of other users who already use this adapter.

My suggestions are:
a. fork the mongoose adapter and make the changes on your fork and use it in your project.
b. make a more flexible PR where you define a `usingLean` adapter option and check it in the methods and use or not. And the default value of it is `false` to be backward compatible.

**Comment by Pitbi** [comment]
Hello,

Indeed, my approach was too brutal. What do you think of this version?

`usingLean` is only accessible for the `find` method of the adapter, but I think it is the most important.

Should we add the `usingLean` param in the `find` action of `moleculer-db`? I don't know if `usingLean` is useful for other adapters. What is the good practice?

Thx for your time.

**Comment by icebob** [comment]
I meant something like this: https://github.com/moleculerjs/moleculer-db/pull/245/commits/dd41f58c929224669af17bfc53201828183de6a1
You can continue using it in other methods.

**Comment by Pitbi** [comment]
Ok thx. :)

But as for my first version it is a strong decision. Since then, come to think of it, I wonder if that might not be an option during the query. Isn't that more flexible?

What do you think?

In my case, your approach suits me very well. It's just for the sake of thinking about it. :)

**Comment by icebob** [comment]
It's much harder to implement it as a method parameter, because the adapter methods called from moleculer-db service, which is a uniform services and you can't put adapter-dependent stuff into it. The only point where you can pass options to the adapter is at the construction:

```js
{
    name: "posts",
    mixins: [DbService],
    adapter: new MongooseAdapter("mongodb://localhost/moleculer-demo", null, { useLean: true }),
    model
}
```

**Comment by Pitbi** [comment]
That's what I thought I understood.

Let's keep this approach then :) 

Thx

**Review by icebob — CHANGES_REQUESTED** [review]
Please add relevant tests as well.

**Comment by Pitbi** [comment]
Hi @icebob,

Sorry for the late response, it was a busy start to the year.

For the tests, is that what you expected?


Thx

**Comment by icebob** [comment]
Partially, you have added integration tests, but need some unit tests as well with the new option to here: https://github.com/moleculerjs/moleculer-db/blob/master/packages/moleculer-db-adapter-mongoose/test/unit/index.spec.js

**Pull request closed without merging**
