### PR TITLE
tests make use mocks to pass without DB engine running

### PR DESCRIPTION
**Pull request by mrkutin**
Implemented test mocks as you suggested. Also did insignificant refactoring .

### CODE REVIEW

**Comment by mrkutin** [comment]
Sure

**Comment by icebob** [comment]
I tried to release it to NPM but I see that you have used the name.

**Comment by mrkutin** [comment]
I can deprecate mine if you want

**Comment by icebob** [comment]
would be good if you can move this npm name to me (icebob) on NPM.

**Comment by mrkutin** [comment]
Will try in an hour

**Comment by mrkutin** [comment]
You are a maintainer now

**Comment by mrkutin** [comment]
I added you as a maintainer. Is it what you asked for?
screen shot 2018-12-19 at 9 28 22 pm

**Comment by icebob** [comment]
Yes, it is. But if I get package info with `npm info` it said I'm not a maintainer:
image

Maybe try it with `npm owner add icebob` command in your repo folder.

**Comment by mrkutin** [comment]
Done!
+ icebob (moleculer-db-adapter-couchdb-nano)

**Comment by icebob** [comment]
Great, it works! Thanks.

**Pull request merged**
