### PR TITLE
Update createCursor function

### PR DESCRIPTION
**Pull request by gcareri**
Assign current q.where in case of text search

### CODE REVIEW

**Comment by HighSoftWare96** [comment]
Related to #153

**Comment by HighSoftWare96** [comment]
@gcareri 
When can this be merged? It is a breaking issue for us...

**Comment by icebob** [comment]
When the unit test has been updated according to changes.

**Comment by HighSoftWare96** [comment]
I've tried that and there is no reason that that test failes...

**Comment by icebob** [comment]
There is it, because the createCursor method source has been changed, so the unit tests should be changed as well.

E.g.: https://travis-ci.org/github/moleculerjs/moleculer-db/jobs/647280165#L253

**Comment by gcareri** [comment]
Hi @icebob, how I can update the test?

**Comment by HighSoftWare96** [comment]
Something like this? 
```javascript
			it("call with full-text search", () => {
				adapter.model.findAll.mockClear();
				adapter.createCursor({
					query: { title: "walter" },
					search: "walter", 
					searchFields: ["title", "content"]
				});
				expect(adapter.model.findAll).toHaveBeenCalledTimes(1);
				expect(adapter.model.findAll).toHaveBeenCalledWith({
					where: {
						title: "walter",
						[Op.or]: [
							{
								title: {
									[Op.like]: "%walter%"
								}
							},
							{
								content: {
									[Op.like]: "%walter%"
								}
							}
						]
					}
				});
			});
```
@gcareri I've tried to make a commit on this PR but I actually can't...

**Comment by icebob** [comment]
Yeah, somethin similar, just would be better to use a different condition in the `where`, and not the same as in fulltext search. E.g.:

```
adapter.createCursor({
    query: { status: 1 },
```

**Comment by HighSoftWare96** [comment]
well @gcareri now you have only to commit the new test :)

**Comment by icebob** [comment]
Solved in https://github.com/moleculerjs/moleculer-db/commit/dc7eaefa35f1e64dedd5c05d40dd1d94c0a79922

**Pull request closed without merging**
