### PR TITLE
verify the hex string is actually valid

### PR DESCRIPTION
**Pull request by cintolas**
If you have a hex string that is 12 characters long, the if statement will succeed, but creating hex string will fail because it MUST be 24 characters long

This patch fixes 2 issues

1. explicitly test via regex that the only thing the string has is valid hex characters
2. verify the length is 24 characters

### CODE REVIEW

**Comment by 0x0a0d** [comment]
you dont need to do this, `ObjectId.isValid` checked this
see `isValid` https://github.com/mongodb/js-bson/blob/v4.2.0/src/objectid.ts#L309
and `checkForHexRegExp` at https://github.com/mongodb/js-bson/blob/v4.2.0/src/objectid.ts#L9

**Comment by cintolas** [comment]
The following will fail without the patch

"use strict";

const { ServiceBroker } = require("moleculer");
const DbService = require("moleculer-db");
const MongoDBAdapter = require("moleculer-db-adapter-mongo");

const broker = new ServiceBroker();

// Create a Mongoose service for `post` entities
broker.createService({
name: "posts",
mixins: [DbService],
adapter: new MongoDBAdapter("mongodb://localhost/moleculer-demo"),
collection: "posts"
});


broker.start()
// Create a new post
.then(() => broker.call("posts.create", {
_id: "aaa.aaa.aaa.",
data: "hello world"
}))
.then(() => broker.call("posts.update", {
_id: "aaa.aaa.aaa.",
data: "hello world2"
}))

// Get all posts
.then(() => broker.call("posts.find").then(console.log));

Here is the error

(node:8304) UnhandledPromiseRejectionWarning: Error: Argument passed in
must be a single String of 12 bytes or a string of 24 hex characters

    at new createFromHexString
(/Users/ppanayotopoulos/mole/node_modules/bson/lib/bson/objectid.js:314:11)

    at MongoDbAdapter.stringToObjectID
(/Users/ppanayotopoulos/mole/node_modules/moleculer-db-adapter-mongo/src/index.js:363:11)

    at MongoDbAdapter.updateById
(/Users/ppanayotopoulos/mole/node_modules/moleculer-db-adapter-mongo/src/index.js:212:55)

    at Service._update
(/Users/ppanayotopoulos/mole/node_modules/moleculer-db/src/index.js:899:24)

    at Service.handler
(/Users/ppanayotopoulos/mole/node_modules/moleculer-db/src/index.js:306:17)

    at
/Users/ppanayotopoulos/mole/node_modules/moleculer/src/utils.js:185:22

    at ServiceBroker.timeoutMiddleware
(/Users/ppanayotopoulos/mole/node_modules/moleculer/src/middlewares/timeout.js:35:14)

    at ServiceBroker.fallbackMiddleware
(/Users/ppanayotopoulos/mole/node_modules/moleculer/src/middlewares/fallback.js:29:11)

    at ServiceBroker.errorHandlerMiddleware
(/Users/ppanayotopoulos/mole/node_modules/moleculer/src/middlewares/error-handler.js:14:10)

    at ServiceBroker.call
(/Users/ppanayotopoulos/mole/node_modules/moleculer/src/service-broker.js:1098:31)

    at /Users/ppanayotopoulos/mole/index.js:24:20

(node:8304) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function
without a catch block, or by rejecting a promise which was not handled with
.catch(). To terminate the node process on unhandled promise rejection, use
the CLI flag `--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
id: 3)

(node:8304) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.

**Comment by 0x0a0d** [comment]
I dont use adapter `mongodb`, I used `mongoose`
Here my code
```js
'use strict'

const { Schema } = require('mongoose')

const { ServiceBroker } = require('moleculer')
const DbService = require('moleculer-db')
const MongoDBAdapter = require('moleculer-db-adapter-mongoose')

const broker = new ServiceBroker({
  nodeID: 'test',
  logger: {
    type: 'Console',
    options: {
      formatter: 'simple',
    }
  },
})

// Create a Mongoose service for `post` entities
broker.createService({
  name: 'posts',
  mixins: [DbService],
  adapter: new MongoDBAdapter('mongodb://localhost/moleculer-demo', { useUnifiedTopology: true }),
  collection: 'posts',
  schema: new Schema({
    data: String
  }),
  modelName: 'tes',
})

broker.start()
  // Remove old test
  .then(() => broker.call('posts.remove', {
    id: 'aaa.aaa.aaa.',
  }))
  // Create a new post
  .then(() => broker.call('posts.create', {
    _id: 'aaa.aaa.aaa.',
    data: 'hello world'
  }))
  .then(() => broker.call('posts.update', {
    id: 'aaa.aaa.aaa.',
    data: 'hello world2'
  }))

  // Get all posts
  .then(() => broker.call('posts.find').then(console.log))
  .then(() => broker.stop())
```
And here result
```bash
INFO  - Moleculer v0.14.15 is starting...
INFO  - Namespace: <not defined>
INFO  - Node ID: test
INFO  - Strategy: RoundRobinStrategy
INFO  - Discoverer: LocalDiscoverer
INFO  - Serializer: JSONSerializer
INFO  - Validator: FastestValidator
INFO  - Registered 13 internal middleware(s).
INFO  - '$node' service is registered.
INFO  - Service '$node' started.
INFO  - MongoDB adapter has connected successfully.
INFO  - 'posts' service is registered.
INFO  - Service 'posts' started.
INFO  - ✔ ServiceBroker with 2 service(s) is started successfully in 38ms.
[ { _id: '6161612e6161612e6161612e', data: 'hello world2', __v: 0 } ]
INFO  - Service '$node' stopped.
WARN  - Mongoose adapter has disconnected.
INFO  - Service 'posts' stopped.
INFO  - ServiceBroker is stopped. Good bye.
```

**Comment by 0x0a0d** [comment]
> If you have a hex string that is 12 characters long, the if statement will succeed, but creating hex string will fail because it MUST be 24 characters long
> 
> This patch fixes 2 issues
> 
> 1. explicitly test via regex that the only thing the string has is valid hex characters
> 2. verify the length is 24 characters

My mistake, i don't see that your pull is for `adapter-mongo` not `mongoose`

**Comment by icebob** [comment]
please note, it won't be merged while the tests failed and there is not unit test for the changes.

**Comment by cintolas** [comment]
> you dont need to do this, `ObjectId.isValid` checked this
> see `isValid` https://github.com/mongodb/js-bson/blob/v4.2.0/src/objectid.ts#L309
> and `checkForHexRegExp` at https://github.com/mongodb/js-bson/blob/v4.2.0/src/objectid.ts#L9
> 12-length
> [mongodb/js-bson#365](https://github.com/mongodb/js-bson/issues/365)

@0x0a0d was correct.  The patch that was applied in january is no longer needed.  Perhaps ObjectID was updated.

Would you like a make a unit test to confirm this?

**Comment by icebob** [comment]
Yes, plz

**Pull request closed without merging**
